interface SeedPais {
    nombre: string;
    id: string;
  }
  
  export const paises: SeedPais[] = [
    { nombre: "Afghanistan", id: "AF" },
    { nombre: "Aland Islands", id: "AX" },
    { nombre: "Albania", id: "AL" },
    { nombre: "Algeria", id: "DZ" },
    { nombre: "American Samoa", id: "AS" },
    { nombre: "Andorra", id: "AD" },
    { nombre: "Angola", id: "AO" },
    { nombre: "Anguilla", id: "AI" },
    { nombre: "Antarctica", id: "AQ" },
    { nombre: "Antigua and Barbuda", id: "AG" },
    { nombre: "Argentina", id: "AR" },
    { nombre: "Armenia", id: "AM" },
    { nombre: "Aruba", id: "AW" },
    { nombre: "Australia", id: "AU" },
    { nombre: "Austria", id: "AT" },
    { nombre: "Azerbaijan", id: "AZ" },
    { nombre: "Bahamas", id: "BS" },
    { nombre: "Bahrain", id: "BH" },
    { nombre: "Bangladesh", id: "BD" },
    { nombre: "Barbados", id: "BB" },
    { nombre: "Belarus", id: "BY" },
    { nombre: "Belgium", id: "BE" },
    { nombre: "Belize", id: "BZ" },
    { nombre: "Benin", id: "BJ" },
    { nombre: "Bermuda", id: "BM" },
    { nombre: "Bhutan", id: "BT" },
    { nombre: "Bolivia", id: "BO" },
    { nombre: "Bosnia and Herzegovina", id: "BA" },
    { nombre: "Botswana", id: "BW" },
    { nombre: "Bouvet Island", id: "BV" },
    { nombre: "Brazil", id: "BR" },
    { nombre: "British Indian Ocean Territory", id: "IO" },
    { nombre: "Brunei Darussalam", id: "BN" },
    { nombre: "Bulgaria", id: "BG" },
    { nombre: "Burkina Faso", id: "BF" },
    { nombre: "Burundi", id: "BI" },
    { nombre: "Cambodia", id: "KH" },
    { nombre: "Cameroon", id: "CM" },
    { nombre: "Canada", id: "CA" },
    { nombre: "Cape Verde", id: "CV" },
    { nombre: "Cayman Islands", id: "KY" },
    { nombre: "Central African Republic", id: "CF" },
    { nombre: "Chad", id: "TD" },
    { nombre: "Chile", id: "CL" },
    { nombre: "China", id: "CN" },
    { nombre: "Christmas Island", id: "CX" },
    { nombre: "Cocos (Keeling) Islands", id: "CC" },
    { nombre: "Colombia", id: "CO" },
    { nombre: "Comoros", id: "KM" },
    { nombre: "Congo", id: "CG" },
    { nombre: "Congo, The Democratic Republic of the", id: "CD" },
    { nombre: "Cook Islands", id: "CK" },
    { nombre: "Costa Rica", id: "CR" },
    { nombre: "Cote D'Ivoire", id: "CI" },
    { nombre: "Croatia", id: "HR" },
    { nombre: "Cuba", id: "CU" },
    { nombre: "Cyprus", id: "CY" },
    { nombre: "Czech Republic", id: "CZ" },
    { nombre: "Denmark", id: "DK" },
    { nombre: "Djibouti", id: "DJ" },
    { nombre: "Dominica", id: "DM" },
    { nombre: "Dominican Republic", id: "DO" },
    { nombre: "Ecuador", id: "EC" },
    { nombre: "Egypt", id: "EG" },
    { nombre: "El Salvador", id: "SV" },
    { nombre: "Equatorial Guinea", id: "GQ" },
    { nombre: "Eritrea", id: "ER" },
    { nombre: "Estonia", id: "EE" },
    { nombre: "Ethiopia", id: "ET" },
    { nombre: "Falkland Islands (Malvinas)", id: "FK" },
    { nombre: "Faroe Islands", id: "FO" },
    { nombre: "Fiji", id: "FJ" },
    { nombre: "Finland", id: "FI" },
    { nombre: "France", id: "FR" },
    { nombre: "French Guiana", id: "GF" },
    { nombre: "French Polynesia", id: "PF" },
    { nombre: "French Southern Territories", id: "TF" },
    { nombre: "Gabon", id: "GA" },
    { nombre: "Gambia", id: "GM" },
    { nombre: "Georgia", id: "GE" },
    { nombre: "Germany", id: "DE" },
    { nombre: "Ghana", id: "GH" },
    { nombre: "Gibraltar", id: "GI" },
    { nombre: "Greece", id: "GR" },
    { nombre: "Greenland", id: "GL" },
    { nombre: "Grenada", id: "GD" },
    { nombre: "Guadeloupe", id: "GP" },
    { nombre: "Guam", id: "GU" },
    { nombre: "Guatemala", id: "GT" },
    { nombre: "Guernsey", id: "GG" },
    { nombre: "Guinea", id: "GN" },
    { nombre: "Guinea-Bissau", id: "GW" },
    { nombre: "Guyana", id: "GY" },
    { nombre: "Haiti", id: "HT" },
    { nombre: "Heard Island and Mcdonald Islands", id: "HM" },
    { nombre: "Holy See (Vatican City State)", id: "VA" },
    { nombre: "Honduras", id: "HN" },
    { nombre: "Hong Kong", id: "HK" },
    { nombre: "Hungary", id: "HU" },
    { nombre: "Iceland", id: "IS" },
    { nombre: "India", id: "IN" },
    { nombre: "Indonesia", id: "ID" },
    { nombre: "Iran, Islamic Republic Of", id: "IR" },
    { nombre: "Iraq", id: "IQ" },
    { nombre: "Ireland", id: "IE" },
    { nombre: "Isle of Man", id: "IM" },
    { nombre: "Israel", id: "IL" },
    { nombre: "Italy", id: "IT" },
    { nombre: "Jamaica", id: "JM" },
    { nombre: "Japan", id: "JP" },
    { nombre: "Jersey", id: "JE" },
    { nombre: "Jordan", id: "JO" },
    { nombre: "Kazakhstan", id: "KZ" },
    { nombre: "Kenya", id: "KE" },
    { nombre: "Kiribati", id: "KI" },
    { nombre: "Korea, Democratic People'S Republic of", id: "KP" },
    { nombre: "Korea, Republic of", id: "KR" },
    { nombre: "Kuwait", id: "KW" },
    { nombre: "Kyrgyzstan", id: "KG" },
    { nombre: "Lao People'S Democratic Republic", id: "LA" },
    { nombre: "Latvia", id: "LV" },
    { nombre: "Lebanon", id: "LB" },
    { nombre: "Lesotho", id: "LS" },
    { nombre: "Liberia", id: "LR" },
    { nombre: "Libyan Arab Jamahiriya", id: "LY" },
    { nombre: "Liechtenstein", id: "LI" },
    { nombre: "Lithuania", id: "LT" },
    { nombre: "Luxembourg", id: "LU" },
    { nombre: "Macao", id: "MO" },
    { nombre: "Macedonia, The Former Yugoslav Republic of", id: "MK" },
    { nombre: "Madagascar", id: "MG" },
    { nombre: "Malawi", id: "MW" },
    { nombre: "Malaysia", id: "MY" },
    { nombre: "Maldives", id: "MV" },
    { nombre: "Mali", id: "ML" },
    { nombre: "Malta", id: "MT" },
    { nombre: "Marshall Islands", id: "MH" },
    { nombre: "Martinique", id: "MQ" },
    { nombre: "Mauritania", id: "MR" },
    { nombre: "Mauritius", id: "MU" },
    { nombre: "Mayotte", id: "YT" },
    { nombre: "Mexico", id: "MX" },
    { nombre: "Micronesia, Federated States of", id: "FM" },
    { nombre: "Moldova, Republic of", id: "MD" },
    { nombre: "Monaco", id: "MC" },
    { nombre: "Mongolia", id: "MN" },
    { nombre: "Montserrat", id: "MS" },
    { nombre: "Morocco", id: "MA" },
    { nombre: "Mozambique", id: "MZ" },
    { nombre: "Myanmar", id: "MM" },
    { nombre: "Namibia", id: "NA" },
    { nombre: "Nauru", id: "NR" },
    { nombre: "Nepal", id: "NP" },
    { nombre: "Netherlands", id: "NL" },
    { nombre: "Netherlands Antilles", id: "AN" },
    { nombre: "New Caledonia", id: "NC" },
    { nombre: "New Zealand", id: "NZ" },
    { nombre: "Nicaragua", id: "NI" },
    { nombre: "Niger", id: "NE" },
    { nombre: "Nigeria", id: "NG" },
    { nombre: "Niue", id: "NU" },
    { nombre: "Norfolk Island", id: "NF" },
    { nombre: "Northern Mariana Islands", id: "MP" },
    { nombre: "Norway", id: "NO" },
    { nombre: "Oman", id: "OM" },
    { nombre: "Pakistan", id: "PK" },
    { nombre: "Palau", id: "PW" },
    { nombre: "Palestinian Territory, Occupied", id: "PS" },
    { nombre: "Panama", id: "PA" },
    { nombre: "Papua New Guinea", id: "PG" },
    { nombre: "Paraguay", id: "PY" },
    { nombre: "Peru", id: "PE" },
    { nombre: "Philippines", id: "PH" },
    { nombre: "Pitcairn", id: "PN" },
    { nombre: "Poland", id: "PL" },
    { nombre: "Portugal", id: "PT" },
    { nombre: "Puerto Rico", id: "PR" },
    { nombre: "Qatar", id: "QA" },
    { nombre: "Reunion", id: "RE" },
    { nombre: "Romania", id: "RO" },
    { nombre: "Russian Federation", id: "RU" },
    { nombre: "RWANDA", id: "RW" },
    { nombre: "Saint Helena", id: "SH" },
    { nombre: "Saint Kitts and Nevis", id: "KN" },
    { nombre: "Saint Lucia", id: "LC" },
    { nombre: "Saint Pierre and Miquelon", id: "PM" },
    { nombre: "Saint Vincent and the Grenadines", id: "VC" },
    { nombre: "Samoa", id: "WS" },
    { nombre: "San Marino", id: "SM" },
    { nombre: "Sao Tome and Principe", id: "ST" },
    { nombre: "Saudi Arabia", id: "SA" },
    { nombre: "Senegal", id: "SN" },
    { nombre: "Serbia and Montenegro", id: "CS" },
    { nombre: "Seychelles", id: "SC" },
    { nombre: "Sierra Leone", id: "SL" },
    { nombre: "Singapore", id: "SG" },
    { nombre: "Slovakia", id: "SK" },
    { nombre: "Slovenia", id: "SI" },
    { nombre: "Solomon Islands", id: "SB" },
    { nombre: "Somalia", id: "SO" },
    { nombre: "South Africa", id: "ZA" },
    { nombre: "South Georgia and the South Sandwich Islands", id: "GS" },
    { nombre: "Spain", id: "ES" },
    { nombre: "Sri Lanka", id: "LK" },
    { nombre: "Sudan", id: "SD" },
    { nombre: "Surinombre", id: "SR" },
    { nombre: "Svalbard and Jan Mayen", id: "SJ" },
    { nombre: "Swaziland", id: "SZ" },
    { nombre: "Sweden", id: "SE" },
    { nombre: "Switzerland", id: "CH" },
    { nombre: "Syrian Arab Republic", id: "SY" },
    { nombre: "Taiwan, Province of China", id: "TW" },
    { nombre: "Tajikistan", id: "TJ" },
    { nombre: "Tanzania, United Republic of", id: "TZ" },
    { nombre: "Thailand", id: "TH" },
    { nombre: "Timor-Leste", id: "TL" },
    { nombre: "Togo", id: "TG" },
    { nombre: "Tokelau", id: "TK" },
    { nombre: "Tonga", id: "TO" },
    { nombre: "Trinidad and Tobago", id: "TT" },
    { nombre: "Tunisia", id: "TN" },
    { nombre: "Turkey", id: "TR" },
    { nombre: "Turkmenistan", id: "TM" },
    { nombre: "Turks and Caicos Islands", id: "TC" },
    { nombre: "Tuvalu", id: "TV" },
    { nombre: "Uganda", id: "UG" },
    { nombre: "Ukraine", id: "UA" },
    { nombre: "United Arab Emirates", id: "AE" },
    { nombre: "United Kingdom", id: "GB" },
    { nombre: "United States", id: "US" },
    { nombre: "United States Minor Outlying Islands", id: "UM" },
    { nombre: "Uruguay", id: "UY" },
    { nombre: "Uzbekistan", id: "UZ" },
    { nombre: "Vanuatu", id: "VU" },
    { nombre: "Venezuela", id: "VE" },
    { nombre: "Viet Nam", id: "VN" },
    { nombre: "Virgin Islands, British", id: "VG" },
    { nombre: "Virgin Islands, U.S.", id: "VI" },
    { nombre: "Wallis and Futuna", id: "WF" },
    { nombre: "Western Sahara", id: "EH" },
    { nombre: "Yemen", id: "YE" },
    { nombre: "Zambia", id: "ZM" },
    { nombre: "Zimbabwe", id: "ZW" },
  ];